package com.beatbet

// Copy of LEAGUE_NAMES in leagues.py: add new leagues to both
val LEAGUE_NAMES = mapOf(
    39 to "England Premier League",
    61 to "France Ligue 1",
    62 to "France Ligue 2",
    72 to "Brazil Serie B",
    78 to "Germany Bundesliga",
    79 to "Germany 2. Bundesliga",
    80 to "Germany 3. Liga",
    88 to "Netherlands Eredivisie",
    94 to "Portugal Primeira Liga",
    98 to "Japan J1 League",
    100 to "Japan J3 League",
    103 to "Norway Eliteserien",
    104 to "Norway OBOS-ligaen",
    106 to "Poland Ekstraklasa",
    107 to "Poland I Liga",
    109 to "Poland II Liga",
    113 to "Sweden Allsvenskan",
    119 to "Denmark Superliga",
    120 to "Denmark 1. Division",
    135 to "Italy Serie A",
    136 to "Italy Serie B",
    140 to "Spain La Liga",
    144 to "Belgium Jupiler Pro League",
    173 to "Bulgaria Vtora Liga",
    204 to "Turkey 1. Lig",
    211 to "Croatia Prva NL",
    219 to "Austria 2. Liga",
    221 to "Austria Regionalliga East",
    235 to "Russia Premier League",
    236 to "Russia FNL",
    251 to "Paraguay Division Intermedia",
    252 to "Paraguay Copa de Primera Clausura",
    266 to "Chile Liga de Ascenso",
    271 to "Hungary NB I",
    272 to "Hungary NB II",
    281 to "Peru Liga 1",
    283 to "Romania SuperLiga",
    287 to "Serbia Prva Liga",
    305 to "Qatar Stars League",
    307 to "Saudi Arabia Pro League",
    308 to "Saudi Arabia Division 1",
    318 to "Cyprus 1. Division",
    333 to "Ukraine Premier League",
    334 to "Ukraine Persha Liga",
    342 to "Armenia Premier League",
    345 to "Czech Chance Liga",
    346 to "Czech Chance Narodni Liga",
    348 to "Czech 3. CFL Group A",
    369 to "Uzbekistan Super League",
    374 to "Slovenia 2. SNL",
    417 to "Bahrain Premier League",
    436 to "Spain Primera RFEF Group 2",
    492 to "Netherlands Tweede Divisie",
    506 to "Slovakia 2. liga",
    563 to "Sweden Division 1 Norra",
    592 to "Sweden Division 2 Norra Götaland",
    596 to "Sweden Division 2 Västra Götaland",
    668 to "Czech 1. Liga U19",
    685 to "Czech 3. CFL Group B",
    862 to "Denmark 3. Division",
)

data class League(val id: Int, val name: String)

/** All leagues, alphabetically by name. */
val LEAGUES: List<League> = LEAGUE_NAMES
    .map { (id, name) -> League(id, name) }
    .sortedBy { it.name.lowercase() }
